# Generated by Django 5.1.3 on 2024-11-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotlinapp', '0005_rename_datetime_appointment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
